### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by dleslie** [Hirrolot/poica#4]
The last few days have seen some major breaking changes to this project; it would help to know what is being planned for the future in order to guage whether this is safe to use in a rolling-upgrade fashion.

**Comment by Hirrolot** [comment]
Thank you for the suggestion, I've added a roadmap: https://github.com/Hirrolot/poica/commit/2b97b13e89d98b12c1800b69a35dde7d653849e4.

**Comment by Hirrolot** [comment]
Moved to: https://github.com/Hirrolot/poica/projects/1.
