### ISSUE TITLE
In generic_link_list.c example, DefLinkedList allocates list with wrong size

### ISSUE THREAD

**Issue by dkrejsa** [Hirrolot/poica#5]
In the generic_link_list.c example shown in README.md, the DefLinkedList macro allocates *list* as follows:

            LinkedList(type) *list = malloc(sizeof(type));                         \

It seems to me that it should be allocated thus:

            LinkedList(type) *list = malloc(sizeof(LinkedList(type)));                         \

**Comment by Hirrolot** [comment]
You're right, fixed.

**Comment by dkrejsa** [comment]
Thanks. Don't forget the copy pasted in the README.md.
